Typescript props fixes (#1302)
* Update BrowserRouter.ts

prevent typescript error TS2322 
```
Types of property 'children' are incompatible.       Type 'Element' is not assignable to type 'Component<any, any>[]'.         Property 'length' is missing in type 'Element'.
```

for the next example:

```
const AppView = () => {
    return (
        <div id="content">
....
        </div>
    )
}

render((
    <BrowserRouter>
        <AppView/>
    </BrowserRouter>
), document.getElementById('app'));
```

* Update Route.ts

fix TS2322 error Property 'children' is missing in type '{ render: (routeProps: RouteComponentProps<any>) => VNode<{}>; }'.
by making the prop children optional

* Update Link.ts

typescript: make replace & innerRef optional as these are not required

* revert browserrouter commit. Switch should be used https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md