Update BrowserRouter.ts
prevent typescript error TS2322 
```
Types of property 'children' are incompatible.       Type 'Element' is not assignable to type 'Component<any, any>[]'.         Property 'length' is missing in type 'Element'.
```

for the next example:

```
const AppView = () => {
    return (
        <div id="content">
....
        </div>
    )
}

render((
    <BrowserRouter>
        <AppView/>
    </BrowserRouter>
), document.getElementById('app'));
```